FROM postgres:9.6-alpine

ADD ./settings.properties /tmp/
ADD ./pr/init_db.sh /docker-entrypoint-initdb.d/
ADD ./pr/createDataBase.sql /pr/

RUN chmod 777 /tmp && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone
